DROP TABLE IF EXISTS Inscription;
DROP TABLE IF EXISTS LigneVente;
DROP TABLE IF EXISTS Possede;
DROP TABLE IF EXISTS Reparation;
DROP TABLE IF EXISTS Atelier;
DROP TABLE IF EXISTS Objet;
DROP TABLE IF EXISTS Vente;
DROP TABLE IF EXISTS Competence;
DROP TABLE IF EXISTS Categorie;
DROP TABLE IF EXISTS Depot;
DROP TABLE IF EXISTS Benevole;
DROP TABLE IF EXISTS Personne;

DROP TYPE IF EXISTS type_mode_paiement;
DROP TYPE IF EXISTS type_resultat_reparation;
DROP TYPE IF EXISTS type_statut_objet;
DROP TYPE IF EXISTS type_etat_objet;
DROP TYPE IF EXISTS type_depot;